# Catppuccin-Mocha
include current-theme.conf

font_size        14.0
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

macos_titlebar_color    background
enabled_layouts         Horizontal
remember_window_size    no
initial_window_width    135c
initial_window_height   32c

shell_integration       no-cursor
cursor_blink_interval   0
cursor_shape            block
cursor_shape_unfocused  hollow

tab_bar_edge            top

map cmd+d launch --location=vsplit
map cmd+w close_window
map cmd+right next_window
map cmd+left previous_window
